spring:
  jpa:
#   전송쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#   테이블 생성 후 data.sql 실행하기
    defer-datasource-initialization: true
#   H2 콘솔 활성화하기
  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true